honeycombio/buildevents

README.md
main.go

This change completely rewrites the README, hopefully in a positive direction.
The changes to buildevents itself are mostly cleanup, with one added feature - looking for an environment variable to indicate which CI provider is in use and including that in events.

pull in forked changes to support multiple CI systems. Update readme.

---

.circleci/config.yml
main.go

* updates the circle build script to push build artifact to github as releases when building a tagged version
* adds a `--version` flag to the binary, set by the github tag and commit hash

Add versioning, pushing releases to github

---

README.md

Adds a missing colon after run in the Circle CI example and avoid a schema error when Circle CI processes the config file.

Fix small typo in Circle CI example configuration

---

README.md

I missed another identical typo! See https://github.com/honeycombio/buildevents/pull/7 for part one of this exciting series.

Fix *one more* run | typo in README

---

README.md

Being able to install with `go get` is nice and all, but it's also useful to be able to get via curl. Update the instructions and examples to mention this.

add binary download instructions

---

README.md
main.go

It would be nice for a URL to exist that will point directly to the trace representing this build.  This change adds output to `buildevents` when run in `build` mode (aka submitting the trace root span). The output from the command, if present, is a URL to the completed build. (If the API key fails to validate, the command is silent.)
```
➜  unset BUILDEVENT_APIKEY
➜  ./buildevents build myBuild 1558499469 success
➜  export BUILDEVENT_APIKEY=$kiwi
➜  ./buildevents build myBuild 1558499469 success
https://ui.honeycomb.io/kiwi/datasets/buildevents/trace?trace_id=myBuild&trace_start_ts=1558499469&trace_end_ts=1558545868
```

build mode emits a link to the full trace to STDOUT

---

main.go

To be good libhoney citizens, let's decorate the user agent field to say that we're running buildevents and pass along what version is in use.
The only real change here is adding `libhoney.UserAgentAddition` - the rest is just moving a few functions around so if we're going to early exit with a usage doc we don't bother initializing libhoney first.

send the buildevents version to Honeyocmb in the useragent field

---

.circleci/config.yml

Add instrumentation to the build config that builds buildevents using the buildevents orb. A little chicken/egg here, but now that there are released versions of the buildevents orb it should be fine.
Addresses Issue #12

Instrument the buildevents build with buildevents

---

main.go

This change should provide a fix for #16 
Visualizing the command `➜  ./buildevents cmd "   aoeu" "  snth    " whitespace -- sleep 2` on both the current master and the fixed branch:

trim leading and trailing whitespace of all command line arguments

---

README.md
circleapi.go
main.go

get a circleci token from the environment to enable private builds.
If the token is absent and the repo does not allow public access, the error you will get says:
```
buildevents - Error detected: 404: Workflow not found
Exited with code 1
```
For public repos, the API calls will work with or without a token.

pass in the circleci api token when appropriate

---

README.md
main.go

This is a simple addition of GitLab-CI environment variables mapping. The list of available variables can be found here: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html

Add support for GitLab-CI provider

---

main.go

The buildevents user-agent field currently contains the version of libhoney and the version of buidevents used. This change adds the CI provider to help us gauge how much effort to put in to compatibility with each provider.

add the ci provider to the user-agent field for Honeycomb analysis

---

circleapi.go

If polling against circleci fails for some reason, this at least passes along the error message that caused the failure.

provide better error messages when polling fails

---

cmd_build.go
cmd_cmd.go
cmd_step.go
cmd_watch.go

This was a regression in the refactor to Cobra - spaces around things like the trace ID cause trace hierarchy to break. All of the positional arguments should lose any whitespace that occurs before or after the argument.

trim spaces around incoming positional arguments

---

README.md
cmd_watch.go

When a CircleCI workflow is configured to run jobs serially, there can be some delay between when one job finishes and the next begins. If you poll the API at just the right point in between one finishing and the next starting, it's possible to get a reply that might otherwise convince you that all jobs are finished (either succeeded or blocked). 
This change will not treat that state as being definitive but will ask the API a few more times to confirm that in fact all jobs are finished and there isn't one just waiting to start. If it finds that the previous check was in fact misleading and there _are_ more jobs to run, it will reset the retry counter until the next time. 
This will extend the total time of the build by 15sec or so, which seems an acceptable delay.
Here's an example of a …

require multiple passes before declaring victory. adding output

---

.circleci/config.yml

buildevents should use the latest version of buildevents to build buildevents.

update to use the latest release of the orb

---

cmd_build.go
cmd_cmd.go
cmd_step.go
cmd_watch.go

Fixes #31 
In the `cmd` case, we need to handle the error returned from the subcommand, or we'll swallow it and return 0.  `watch` manually called `os.Exit(1)`, but cobra supports a `RunE` method on commands that has an `error` return.
Switch to `RunE`, return the proper error in `cmd_cmd.go`, and return the error instead of calling `os.Exit` in `cmd_watch.go`

switch to using RunE instead of Run for our commands

---

.circleci/config.yml

As a convenient place to keep an example of how `add_context` should be used, let's add a record of the size of the artifacts produced by the `build` step in buildevent's build.
Depends on #28 - after that lands I'll rebase this and then the build should run.

provide example of add_context in the buildevents build

---

.circleci/config.yml

v0.2.0 of the orb has a bug that's fixed in 0.2.1. Bumping to stay current.

bump orb version

---

.circleci/config.yml

add a pretty tiny job to test buildevents `cmd` with both `true` and `false` as commands, to make sure the former succeeds and the latter fails.

add smoketest job to make sure exit statuses are propagated

---

common.go

Removed the prefix `JENKINSX_` from all custom fields for this provider.

renamed jenkins x custom fields to match our docs

---

.circleci/config.yml

Using buildevents in the `cibuilds/base` docker image gave a confusing "file not found" error. Turns out alpine linux uses musl instead of libc, but disabling CGO is supposed to fix everything.

disable cgo for alpine-linux compatability

---

.circleci/config.yml

This is a bit chicken-vs-egg, but the buildevents version that works for finishing the trace after publishing is the one we just tagged (0.4.4).  Previous releases were still uploading the files to github, but the build was being flagged as failing on the publish step because of the cgo problem.
The orb that pulls in v0.4.4 of buildevents is v0.2.3, so bump our dep to that.

bump the orb version to 0.2.3

---

go.mod
go.sum
vendor/github.com/jszwedko/go-circleci/circleci.go
vendor/modules.txt

Taking the change suggested in #46 and using the new copy of go-circleci that contains it.

use updated dependency on corrected  circleci api

---

cmd_cmd.go

This way we can consume any output that the cmd itself generates

Cmd annotates with arbitrary fields until after the cmd is run

---

go.mod
go.sum
vendor/github.com/jszwedko/go-circleci/circleci.go
vendor/modules.txt

Update `github.com/maplebed/go-circleci` to fix a couple of v2 api breakages (the most recent one causes the `watch` command to 404 for all its requests).

update go-circleci dep

---

main.go

defers don't get run when os.Exit is called, so we need to explicitly call libhoney.Close to
make sure that events from `buildevents cmd` with a non-zero exit status get sent.

Call libhoney.Close when commands return an error.

---

cmd_cmd.go

The previous version used two goroutines calling `io.Copy`.
Unfortunately it did not check the return value of `io.Copy` and in
production we saw some hangs which looked like they might be caused if
one or both `io.Copy`s failed but `cmd.Wait` didn't return.
This version is much simpler and just hooks up the parent's Stdout/Stderr
to the child's Stdout/Stderr directly.

Simplify subprocess IO management.

---

cmd_cmd.go

Show usage for errors returned by Args:
```
❯ go run github.com/honeycombio/buildevents cmd build step name false
Error: use `--` to signify shell command
Usage:
buildevents cmd [flags] BUILD_ID STEP_ID NAME -- [shell command to execute]
Flags:
-h, --help   help for cmd
Global Flags:
-a, --apihost string    [env.BUILDEVENT_APIHOST] the hostname for the Honeycomb API server to which to send this event (default "https://api.honeycomb.io")
-k, --apikey string     [env.BUILDEVENT_APIKEY] the Honeycomb authentication token
-d, --dataset string    [env.BUILDEVENT_DATASET] the name of the Honeycomb dataset to which to send these events (default "buildevents")
-f, --filename string   [env.BUILDEVENT_FILE] the path of a text file holding arbitrary key=val pairs (multi-line-capable, logfmt style) …
```

Silence usage on cmd error.  Fixes #45

---

cmd_root.go
common.go
main.go

I kept with the naming that the other providers used where possible. For PRs there is both ID and Number, the first for PRs created using Azure Repos and the second for PRs created in Github.

Add support for Azure Pipelines

---

README.md
cmd_root.go
common.go
main.go

This adds support/automatic detection of GitHub Actions as a CI provider.
They have a doc here listing the env vars provided by the runner, from which I pulled what looked like the most relevant ones: https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables

add GitHub actions as a supported CI provider

---

README.md

With the old value this fetches a text document that contains "Not found"
and raises "Not: command not found in TravisCI." I think being explicit
with the architecture here is fine as by default it is what TravisCI
will use.

Correct a download link

---

cmd_watch.go

keep track of whether or not we have blocked jobs.  this should let us know for certain when we're actually done, so we can stop waiting sooner.
We can stop and declare the build finished as soon as there are no running jobs (minus the watch job itself) and no blocked jobs.
Simplify the loop inside `evalWorkflow` to have no early returns, and just set another flag - `anyRunning`, which is true for jobs in either the `queued` or `running` circleci states.
The loop inside `waitCircle` continues to confound and is next on the list of places we should simplify, imo.

make watch job more efficient

---

README.md
cmd_cmd.go

When using something like https://github.com/puppetlabs/rspec_honeycomb_formatter , it would be nice to connect the individual spans to the bigger picture of the buildevent steps and commands. This change uses the beeline's `PropagationContext` marshaling to pass on the current event to the called command.
In the style of the rest of the HONEYCOMB_* environment variables and the similarily named `X-Honeycomb-Trace` HTTP header, this establishes `HONEYCOMB_TRACE` to pass the propagation context to other processes.
I'm also adopting this naming for the two other projects my team is maintaining where trace contexts are passed around:
- https://github.com/puppetlabs/puppet_litmus/pull/355
- https://github.com/puppetlabs/rspec_honeycomb_formatter/pull/12

Add beeline-style propagation of the cmd context to called commands

---

common.go

The ui.honeycomb.com URLs for datasets with spaces in the name use a `-` (dash) for encoding that space. This change fixes the `buildURL` function to also use dashes for spaces, instead of exposing the space character.
This fixes #72

Encode spaces in dataset names for the URL

---

.github/CODEOWNERS

Adds CODEOWNERS file for @honeycombio/integrations-team.

Add codeowners with integration-team

---

cmd_cmd.go

closes https://github.com/honeycombio/buildevents/issues/79
Adds a `-q` flag to `cmd`.

added quiet option to cmd

---

.circleci/config.yml

PRs from forks were [unauthorized](https://app.circleci.com/pipelines/github/honeycombio/buildevents?branch=pull%2F80) to run CI builds due to a restricted secrets context. Changes in this PR are following the same pattern as [otel-exporter-python](https://github.com/honeycombio/opentelemetry-exporter-python/pull/21)
* add build_forked workflow without buildevents, so forked PRs can run builds
* exclude forked PRs from the main workflow

Ensure PRs from forks can run CI checks

---

README.md
cmd_root.go
common.go
main.go

add bitbucket support

---

cmd_build.go
cmd_cmd.go
cmd_step.go
cmd_watch.go

This is an option for addressing https://github.com/honeycombio/buildevents/issues/75
Loading the `$BUILDEVENT_FILE` after default fields are added to the event
allows them to be overridden. This will make it possible to add spans nested
under children of the root span (by overriding `trace.parent_id`), and will
also add support for customizing other default fields like `service_name`.

Add support for overriding default fields

---

.circleci/config.yml
README.md

(This is a precursor to adding the arm release to
https://github.com/honeycombio/buildevents-orb)

Build an arm64 release

---

README.md

This is pretty gross and not very ergonomic, but I'm not sure if there are better ways.
It looks like other CI providers have much better ways to do some of this instrumentation.
Tests on https://gitlab.com/zoidyzoidzoid/buildevents-mirror/-/pipelines
I'm gonna copy this and test it on a large internal repo today.

Another GitLab CI example

---

cmd_cmd.go

cmd: Forward stdin.

---

.circleci/config.yml

dependabot does not have access to secrets necessary to watch builds
in action: https://app.circleci.com/pipelines/github/honeycombio/buildevents/266/workflows/a030bb30-ea38-40eb-9074-915099387362

stop watching dependabot builds

---

README.md
cmd_cmd.go

I think this could be considered a solution to https://github.com/honeycombio/buildevents/issues/88 but maybe not since it doesn't try to do any sort of auto-detection of shells.
Add a new flag on the `cmd` subcommand to run with an alternate shell. My personal use case is switching it to `/bin/sh` for alpine images.

Allow specifying an alternative shell

---

go.mod
go.sum

Bumps libhoney-go to v1.15.6.
- bump libhoney-go to v1.15.6 in go.mod/sum

Bump libhoney-go to v1.15.6

---

.circleci/config.yml

When publishing a new release, we create a GitHub release but create it as a public release. We should create draft releases so we can update the release notes before publishing.
- set the `-draft` flag to create a draft gh release during circle publish job

Create draft GitHub release during publish

---

cmd_watch.go

- `buildURL` in the watch command calls libhoney's `VerifyAPIKey` which calls out to the Honeycomb API. If there is an error in this step, the entire build will fail. This could happen both if your API Key is not valid or if the Honeycomb API is inaccessible. If this step fails we should log and continue, rather than returning an error and failing the entire build. Note that this is similar to how `buildURL` is currently handled by the build command: https://github.com/honeycombio/buildevents/blob/main/cmd_build.go#L46
- If `buildURL` fails, log and continue rather than erroring.

do not fail the build if buildURL does not verify API key

---

.circleci/config.yml

- previous release created 4 separate draft GH releases with individual artifacts in each
- make a single draft release with all the artifacts
- test: https://app.circleci.com/pipelines/github/honeycombio/buildevents/328/workflows/af595561-551c-4629-bb85-77beda424cbb/jobs/1376

Fix release publish

---

common.go

- The error message `Unable to create trace URL: unable to verify API key` could be clearer. This PR prints the underlying error. Here how I came up to this: 
- I had misread the `BUILDEVENT_APIKEY` in the docs and actually used `BUILDEVENT_API_KEY`
- I thus wrongly assumed there was some issue elsewhere because even re-reading the docs, the missing `_` is hard to see (that's on me!) 
- I applied the patch in this PR to actually see what was the issue. 
- It showed me a message about the key being blank, so it finally clicked and I saw the missing `_`.
At this point, I thought I'd rather submit a PR just in case you find it appropriate :) 
This (probably?) addresses https://github.com/honeycombio/buildevents/issues/92.
- It just prints the underlying error from `libhoney` when it cannot …

Display underlying error when verifying API key

---

main.go

- `buildevents cmd` shadows any specific exit code returned by commands it was asked to run.
- This prevents CI scripts that rely on specific exit codes to detect, for example, soft failures (that was what happened to us in this case). 
- When `buildevents cmd` is called, if there is an error, it will check if that's a `exec.ExitError` and will return the associated exit code instead of plainly exting with a code `1`. 
I tested this on our own CI system with success. 
<details>
<summary>Small snippet if you want to see for yourself</summary>
```
~/play/foobar $ ./foobar
27
Error: exit status 27
Usage:
hugo [flags]
Flags:
-h, --help   help for hugo
exit status 27
here 27
~/play/foobar $ echo $?
27
```
```go
package main
import (
"errors"
"fmt"
"os"
"os/exec"
"github.com/spf13/cobra"
)
func …
```

Return underlying exit code when running commands

---

cmd_root.go

In reworking the commits for the new version, I mistakenly restored a default value for the dataset that shouldn't be there. This removes it. Defaults are now applied in code based on logic.
Requires release of 0.9.1.

remove erroneous default value

---

.circleci/config.yml

- closes #142 
- update ci image to cimg/go:1.18 (which is currently on 1.18.1)

maint: update ci image to cimg/go:1.18

---

common.go

We'd like to allow honeycombio/gha-buildevents to [differentiate itself](https://github.com/honeycombio/gha-buildevents/blob/v1.0.6/src/buildevents.ts#L28) from using `buildevents` manually inside GHA. Adds this new identifier to the GHA-related provider setup, so we still get these ENV variables set.

add gha-buildevents as GHA provider alias

---

cmd_root.go

As part of introducing Environments and Services, we also support users of Buildevents to configure the `service-name` associated to Build Events. However, for Build Events, the configuration `dataset` is also still valid to allow users to name the bucket into which events from their pipelines and builds are sent to. 
We are removing the "Warning" prompting users to change their dataset config to be called service name.
* Remove the warning to change dataset to service name
* Ensure we are setting a default value if no dataset or service name is set (configured)
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1202842340194784

Removes warning when `dataset` is configured without setting `service-name`

---

cmd_cmd.go

We noticed for Github Actions or even CircleCI buildevents that the step or command that represents the failure does not include the boolean field error set to `true`
**We use this value to signal the error state in the UI:**
**AND in the calculation to display error rates on the Home page for Buildevents:** 
Includes the field error true along with sending status failed and failure reason for a span

Include field `error` true for spans representing failure results

---

.circleci/config.yml

Removes using buildevents when building buildevents. This is because we'd need to expose a valid CircleCI token in our config which can be tricky as this is a public repo.
- Removes buildevents from circle CI config

ci: Remove buildevents from circle config

---

LICENSES/github.com/facebookgo/clock/LICENSE
LICENSES/github.com/facebookgo/limitgroup/license
LICENSES/github.com/facebookgo/muster/license
LICENSES/github.com/honeycombio/beeline-go/propagation/LICENSE
LICENSES/github.com/honeycombio/beeline-go/propagation/NOTICE
LICENSES/github.com/honeycombio/libhoney-go/LICENSE
LICENSES/github.com/honeycombio/libhoney-go/NOTICE
LICENSES/github.com/jszwedko/go-circleci/LICENSE
LICENSES/github.com/klauspost/compress/LICENSE
LICENSES/github.com/klauspost/compress/internal/snapref/LICENSE
LICENSES/github.com/klauspost/compress/zstd/internal/xxhash/LICENSE.txt
LICENSES/github.com/kr/logfmt/Readme
LICENSES/github.com/spf13/cobra/LICENSE.txt
LICENSES/github.com/spf13/pflag/LICENSE
LICENSES/github.com/vmihailenco/msgpack/v5/LICENSE
LICENSES/github.com/vmihailenco/tagparser/v2/LICENSE
LICENSES/gopkg.in/alexcesaro/statsd.v2/LICENSE
RELEASING.md

It is a legal requirement to include the license of any software used to build distributable artefacts. This PR uses [go-licenses](https://github.com/google/go-licenses) to determine and extract the license files for the dependencies for buildevents.
It also updates the releasing.md to include the steps to ensure this is updated as part of the release process.
- Add licenses directory that contains the license for each project dependency
- Updates releasing.md with steps to re-create the set of dependency licenses

maint: Add dependency license files

---

.github/CODEOWNERS

Transfers ownership of the project to the API Team

maint: transfer ownership to API team

---

.github/PULL_REQUEST_TEMPLATE.md
.github/dependabot.yml
.github/release.yml
.github/workflows/add-to-project-v2.yml
RELEASING.md

- finish handoff of repo to pipeline team
- add github workflow for github project
- remove reviewers section with api-team 
- removing reviewers altogether bc dependabot will just use CODEOWNERS file to assign
- group dependencies into 1 PR
- update PR template and release yml
- update releasing guide with more detail

maint: update repo for pipeline team ownership

---

cmd_watch.go

This only applies to buildevents used in CircleCI.
In Honeycomb, we can query against the `watch` step of the buildevents trace to find out how often jobs are failing. Unfortunately, this does not include the list of the failed jobs, reducing its effectiveness, as usually if you are looking at the amount of failed jobs you'd also like to know which jobs failed. 
As an example of reduced effectiveness, this prevents BubbleUp from showing which jobs are responsible for a failing SLO on % succesful builds.
We have the list of failed jobs available to us when we call the circleCI API to find out if there are any failed jobs. This PR wires through a list of names of those failed jobs back through the responses so we can include it as a span attribute in the `watch` event.
If we can test with …

feat: return list of failed jobs in cmd watch
