honeycombio/buildevents

.circleci/config.yml

expected followup PR - once circle is successfully building buildevents, I will enable pushing built binaries to github releases

adding build configs for circleci

---

README.md
go.mod
go.sum
main.go
vendor/github.com/kr/logfmt/.gitignore
vendor/github.com/kr/logfmt/Readme
vendor/github.com/kr/logfmt/decode.go
vendor/github.com/kr/logfmt/scanner.go
vendor/github.com/kr/logfmt/unquote.go
vendor/modules.txt

simplest thing that could work

---

.circleci/config.yml
README.md

This is mostly @hramos's change but with a few changes to account for changes to master since his fork.

Add Macos builds

---

README.md
cmd_root.go
common.go
main.go

Adding Jenkins X Provider with respective fields.

added Jenkins X environment variable and specific fields

---

cmd_watch.go

After talking about #43 we came to the conclusion that the watch timeout was just too short. This change increases it from 15 seconds to 2 minutes. 
It would be annoying though, to overreport the duration of builds by 2 minutes when they have (correctly) unfinished jobs.  So this change also records when `bulidevents` _first_ thinks it has finished the build and uses that as the end time rather than the time it finally agrees that it really has finished for real and returns. The effect will be that the trace duration will be the time the build was actually running, though CircleCI will show the build as being 2 minutes longer with the `watch` job being the only thing running for the final two minutes.
This seems like an acceptable oddness to accept, given that it is only in the cases …

increasing watch timeout, backdating finished time when ending with unfinished jobs

---

main.go

Fixing the Azure-Pipelines const variable

fix providerAzurePipelines in main.go

---

CHANGELOG.md

Prepare for 0.5.0 release, add changelog

---

.circleci/config.yml

* simplify workflow, based on https://github.com/honeycombio/opentelemetry-exporter-python/blob/main/.circleci/config.yml#L180
* publish a _draft_ release to GitHub

Tweak circle config

---

CHANGELOG.md

update changelog for 0.5.2 release

---

CHANGELOG.md

Adds changelog entry for v0.6.0 release

Update changelog for v0.6.0 release

---

CHANGELOG.md
RELEASING.md

Prepares the v0.7.0 release.
- add changelog entry for v0.7.0

Prepare v0.7.0 release

---

.circleci/config.yml

- closes #96 
- working directory was causing issues with the new image, and AFAICT it's not necessary

update ci image

---

CHANGELOG.md

Prepares the v0.7.2 release.
- Adds changelog entry.

Prepare v0.7.2 release

---

CHANGELOG.md

prepare 0.8.0 release

---

CHANGELOG.md

Prep for release of 0.9.0

---

CHANGELOG.md

Update changelog (bug fix only).

Prep for release 0.9.1

---

CHANGELOG.md

Prepare 0.9.2 release

---

CHANGELOG.md

- Update changelog in prep for 0.10.0 release

prep for v0.10.0

---

CHANGELOG.md

release: prepare 0.12.0

---

CHANGELOG.md

- Fix openSSL CVE by re-releasing

prep 0.12.1

---

CHANGELOG.md

Update the changelog in preparation for `v0.14.0`

rel: prepare 0.14.0

---

CHANGELOG.md

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205046216051399

rel: prepare 0.15.0

---

CHANGELOG.md

rel: prepare 0.16.0

---

CHANGELOG.md

- new release
- update changelog

rel: prep v0.17.0
